# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'OC_weibo' do

pod 'AFNetworking'
pod 'SDWebImage'
pod 'SVProgressHUD'

end

target 'OC_weiboTests' do

end

target 'OC_weiboUITests' do

end

